# Generated by Django 2.2 on 2019-11-19 17:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opendata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpendataHistoric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('alt', models.FloatField(blank=True, null=True)),
                ('cate', models.TextField(blank=True, null=True)),
                ('cod', models.TextField(blank=True, null=True)),
                ('cod_old', models.FloatField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('ico', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('nom', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'opendata_historic',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
